FROM lsstsqre/centos:d_latest
ENV PYTHONUNBUFFERED True
RUN source /opt/lsst/software/stack/loadLSST.bash \
    && mamba install -y \
        flask \
        gunicorn \
        google-cloud-pubsub \
        google-cloud-sdk \
        google-cloud-storage \
    && pip install --no-input \
        cloudevents
