FROM lsstsqre/centos:d_latest
ENV PYTHONUNBUFFERED True
RUN source /opt/lsst/software/stack/loadLSST.bash \
    && mamba install -y \
        flask \
        gunicorn \
        python-confluent-kafka \
    && pip install --no-input \
        cloudevents
