---
name: "Build and test initializer"
on:
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - '.github/workflows/build-init-job.yaml'
      - '.github/workflows/_matrix-gen.yaml'
      - '.github/actions/**'
      - 'config/**'
      - 'pipelines/**'
      - 'python/initializer/**'
      - 'python/shared/**'
      - 'tests/**'
      - 'init-output-run/Dockerfile'
  pull_request:
    paths:
      - '.github/workflows/build-init-job.yaml'
      - '.github/workflows/_matrix-gen.yaml'
      - '.github/actions/**'
      - 'config/**'
      - 'pipelines/**'
      - 'python/initializer/**'
      - 'python/shared/**'
      - 'tests/**'
      - 'init-output-run/Dockerfile'
  workflow_dispatch:

permissions:
  packages: write

env:
  IMAGE_NAME: prompt-init
  IMAGE_DOCKERDIR: init-output-run
  BASE_IMAGE: ghcr.io/${{ github.repository_owner }}/prompt-base

jobs:
  matrix-gen:
    uses: ./.github/workflows/_matrix-gen.yaml

  # Do testing and building in separate jobs to keep total disk usage down
  test-service:
    needs: matrix-gen
    strategy:
      matrix:
        baseTag: ${{ fromJSON(needs.matrix-gen.outputs.matrix) }}
    name: Test service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: "Test service against ${{ env.BASE_IMAGE }}:${{ matrix.baseTag }}"
        uses: ./.github/actions/test-service
        with:
          baseImage: ${{ env.BASE_IMAGE }}
          baseTag: ${{ matrix.baseTag }}
          ghcr_user: ${{ github.actor }}
          ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  update-init-image:
    name: Update init image
    needs:
      - matrix-gen
      - test-service
    runs-on: ubuntu-latest
    strategy:
      matrix:
        baseTag: ${{ fromJSON(needs.matrix-gen.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and push image
        uses: ./.github/actions/update-dev-image
        with:
          imageName: ${{ env.IMAGE_NAME }}
          dockerDir: ${{ env.IMAGE_DOCKERDIR }}
          baseImage: ${{ env.BASE_IMAGE }}
          baseTag: ${{ matrix.baseTag }}
          ghcr_user: ${{ github.actor }}
          ghcr_token: ${{ secrets.GITHUB_TOKEN }}
